#!/bin/bash
trap "echo TRAP!!; exit" SIGTERM SIGINT SIGHUP
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python cifar10_multi_gpu_train.py \
  --num_gpus=8 \
  --max_steps=100000 \
  --batch_size=128 \
  --batch_size_upper=128 \
  --batch_size_lower=32 \
  --apply_pbt=true \
  --pbt_ready_frequency=50 \
  --pbt_truncate_percentage=20 \
  --pbt_population_size=40 \
#  --debug true
